% dar de alta una función
%fun = @(x) x(1).*x(1)+x(2).*x(2)+2*sin(x(1))*sin(x(2));

% Ackley
fun = @(x) -20.*exp(-0.2.*sqrt(0.5.*(x(1).^2 + x(2).^2)))...
    -exp(0.5.*(cos(2.*pi.*x(1)) + cos(2.*pi.*x(2)))) + exp(1) + 20;
% optimization
options = optimoptions("ga","MaxGenerations",500,...
    "Display","diagnose","PlotFcn","gaplotbestf",...
    "CreationFcn","gacreationuniform","MutationFcn","mutationuniform",...
    "PopulationSize",100,"CrossoverFcn","crossoverscattered")
[X,f]=ga(fun,2,[],[],[],[],[],[],[],options)